<div id="footer"><div class="wrapper">

	<p><strong>Parque Satélite</strong></p>
	<p class="mt10">Av. Gustavo Baz No. 51, Colonia Xocoyahualco</p>
	<p>Zona Satélite, Tlalnepantla, Estado de México</p>
	<p><a href="mailto:ventas@parquesatelite.com" target="_blank">ventas@parquesatelite.com</a></p>
	<p>Tel. (55) 12-04-12-62</p>
	
	<p class="mt20 mb20"><strong>Un proyecto de</strong></p>
	
	<div id="gwep">
		<a href="http://gwep.com.mx" target="_blank"><img src="images/GWEP_logo.png" alt="GWEP GROUP" /></a>
		<a href="http://www.gavacapital.com" target="_blank"><img src="images/GAVA_logo.png" alt="GAVA CAPITAL" /></a>
	<div class="clearfix"></div></div>
	
	<a href="#" id="top">TOP</a>

<div class="clearfix"></div><!-- /clearfix -->
</div><!-- / wrapper --></div><!-- / footer -->


