	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
		
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<meta name="author" content="Sandra Bermudez @ bulabe.com" />
	
	<meta property="og:title" content="Parque Satélite" />
	<meta property="og:type" content="website" />
	<meta property="og:description" content="Preventa de Departamentos Nuevos desde $3,100,000 en Tlalnepantla, Estado de México en la Zona Conurbada del DF. Amplios Departamentos con acabados de Lujo" />
	<meta property="og:url" content="http://parquesatelite.com" />
	<meta property="og:image" content="http://parquesatelite.com/images/Parque_Satelite_og.jpg" />
	
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Quattrocento|Quattrocento+Sans:400,700" />
	<link rel="stylesheet" type="text/css" href="style.css" />
	
	<script type="text/javascript" src="js/jquery-1.6.2.min.js"></script>
	<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
	<script type="text/javascript" src="js/fancydropdown.js"></script>
	<script type="text/javascript" src="js/jquery.frontend.js"></script>
	
	<script>
/* GOOGLE ANALYTICS */
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51782211-1', 'parquesatelite.com');
  ga('send', 'pageview');
</script>

<!-- Google Code para etiquetas de remarketing -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1014923954;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/1014923954/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

