
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?3ffJpfACg4leqNOFKJ1Doj9QcEsPuBZA";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->


<div id="header">
<div class="extended">

<a href="index.php" target="_self" id="logo">Satélite</a>	
	
<ul id="menu">
	<li><a href="index.php" target="_self">Parque Satélite</a></li>
	<li><a href="video.php" target="_self">Video</a></li>
	<li><a href="amenidades.php" target="_self">Amenidades</a></li>
	<li><a href="departamentos.php" target="_self">Departamentos</a></li>
	<li><a href="ubicacion.php" target="_self">Cómo llegar</a></li>
	<li><a href="contacto.php" target="_self">Contacto</a></li>
    <div class="clearfix"></div><!-- /clearfix -->
</ul>

<div class="clearfix"></div><!-- /clearfix -->

<div class="clearfix"></div><!-- /clearfix -->
</div><!-- / WRAPPER -->
</div><!-- / HEADER -->

<ul id="social">
	<div class="extended">
	<li><a href="contacto.php" target="_self" class="activo">Mándanos un e-mail</a></li>
	<li><a href="agenda_una_cita.php" target="_self">Agenda una cita</a></li>
	<li><a href="te_llamamos.php" target="_self">Nosotros te llamamos</a></li>
	<div class="clearfix"></div><!-- /clearfix -->
	</div>
</ul>

<div id="call-to-call">
	<p>Haz una cita: (55) 12-04-12-62</p>
</div>