

<div id="opacidad">
<div id="reply">
<a href="#" id="saltar">X</a>

<h1 class="mb10">Invitación VIP</h1>
<p class="mb10">Tenemos el honor de invitarte el próximo</p>
<p class="mb10"><strong>sábado 14 y domingo 15 de febrero</strong> al</p>
<p class="mb10">COCTEL DE PREVENTA Y LANZAMIENTO DE LA</p>

<img src="images/parque_satelite_3a_torre.png" class="mb10"/>
<p>del desarrollo</p>
<img src="images/parque_satelite_logo_promo.png" alt="Parque Satélite" class="mb10"/>

<p class="mb10">con modernos departamentos desde 100m<sup>2</sup></p>

<img src="images/parque_satelite_habra_promociones.png"/>
<a href="invitacion-torre-3/registro.php" target="_self" id="registro">Agenda tu recorrido</a>
	
	


</div></div><!-- /opacidad, reply -->

